name = "aura-core"
main = "src/index.js"
compatibility_date = "2024-12-01"

# Wrangler v4+ Node compatibility
compatibility_flags = ["nodejs_compat"]

[[kv_namespaces]]
binding = "AURA_KV"
id = "9c2ba111589e48c6ba5ad1b924ae8809"
